In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
list(y)

[0, 1, 2, 3, 4]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [4]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [6]:
X_test

array([[2, 3],
       [8, 9]])

In [7]:
y_train

[2, 0, 3]

In [8]:
y_test

[1, 4]

# On a slightly larger dataset

### We are splitting X into two variables: X_train and X_test
### We are also splitting y into two variables: y_train and y_test

In [9]:
from sklearn.datasets import make_classification

In [10]:
X, y = make_classification(
    n_features=2, n_redundant=0, n_informative=2, random_state=1, n_clusters_per_class=1
)

In [12]:
X.shape

(100, 2)

In [13]:
y.shape

(100,)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [15]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(67, 2)
(33, 2)
(67,)
(33,)
